pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                withCredentials([file(credentialsId: '66d871b4-0e0f-4b24-ad48-12c1a66408ab', variable: 'SSH_KEY')]) {
                    sh '''
                        ssh -i $SSH_KEY ubuntu@34.201.72.126 "
                            [ ! -d /home/ubuntu/ParkalotGDSC ] && git clone https://github.com/Autumn2OO5/ParkalotGDSC.git /home/ubuntu/ParkalotGDSC
                            cd /home/ubuntu/ParkalotGDSC && git pull origin main
                        "
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                withCredentials([file(credentialsId: '66d871b4-0e0f-4b24-ad48-12c1a66408ab', variable: 'SSH_KEY')]) {
                    sh '''
                        ssh -i $SSH_KEY ubuntu@34.201.72.126 "
                            cd /home/ubuntu/ParkalotGDSC && docker build -t parkalot-app .
                        "
                    '''
                }
            }
        }

        stage('Verify') {
            steps {
                withCredentials([file(credentialsId: '66d871b4-0e0f-4b24-ad48-12c1a66408ab', variable: 'SSH_KEY')]) {
                    sh '''
                        ssh -i $SSH_KEY ubuntu@34.201.72.126 "
                            docker image inspect parkalot-app > /dev/null 2>&1
                        "
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([file(credentialsId: '66d871b4-0e0f-4b24-ad48-12c1a66408ab', variable: 'SSH_KEY')]) {
                    sh '''
                        ssh -i $SSH_KEY ubuntu@34.201.72.126 "
                            docker stop parkalot-container || true
                            docker rm parkalot-container || true
                            docker run -d --name parkalot-container -p 3001:3001 parkalot-app npm run frontend:dev
                        "
                    '''
                }
            }
        }

    }
}