pipeline {
    agent any

    stages {
        stage('Deploy to EC2') {
            steps {
                withCredentials([file(credentialsId: 'jenkins-pem', variable: 'SSH_KEY')]) {
                    sh '''
chmod 400 $SSH_KEY

ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@34.201.72.126 << 'EOF'
if [ ! -d "/home/ubuntu/ParkalotGDSC" ]; then
    git clone https://github.com/Autumn2OO5/ParkalotGDSC.git /home/ubuntu/ParkalotGDSC
fi

cd /home/ubuntu/ParkalotGDSC
git pull origin main

docker stop parkalot-container || true
docker rm parkalot-container || true

docker build -t parkalot-app .

docker run -d \
  --name parkalot-container \
  -p 3001:3001 \
  parkalot-app \
  npm run frontend:dev
EOF
'''
                }
            }
        }
    }
}