pipeline {
    agent any

    stages {

        stage('Deploy to EC2') {
            steps {
                withCredentials([file(credentialsId: 'jenkins-server.pem', variable: 'SSH_KEY')]) {
                    sh '''
                    chmod 400 $SSH_KEY

                    ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_PUBLIC_IP << 'EOF'

                    if [ ! -d "~/ParkalotGDSC" ]; then
                        git clone https://github.com/Autumn2OO5/ParkalotGDSC.git ~/ParkalotGDSC
                    fi

                    cd ~/ParkalotGDSC
                    git pull origin main

                    docker stop parkalot-container || true
                    docker rm parkalot-container || true

                    docker build -t parkalot-app .

                    docker run -d \
                        --name parkalot-container \
                        -p 3001:3001 \
                        parkalot-app \
                        npm run dev

                    EOF
                    '''
                }
            }
        }
    }
}